### ISSUE TITLE
Error: Cannot find module './frameworks/cocos2d-html5/moduleConfig.json'

### ISSUE THREAD

**Issue by derofim** [TimMensch/Cocos2d-js-ES2016-Flow#1]
Full log: https://gist.github.com/derofim/72ad99f4bf6f8e0a36e7
[12:51:34] Using gulpfile D:\OpenServer\domains\cocostest.com\Cocos2d-js-ES2016-Flow-master\gulpfile.js
[12:51:34] Starting 'cocos2d'...
[12:51:34] 'cocos2d' errored after 981 μs
[12:51:34] Error: Cannot find module './frameworks/cocos2d-html5/moduleConfig.json'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at getCocosList (D:\OpenServer\domains\cocostest.com\Cocos2d-js-ES2016-Flow-master\gulpfile.js:99:24)
    at Gulp.<anonymous> (D:\OpenServer\domains\cocostest.com\Cocos2d-js-ES2016-Flow-master\gulpfile.js:153:21)
    at module.exports (D:\OpenServer\domains\cocostest.com\Cocos2d-js-ES2016-Flow-master\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (D:\OpenServer\domains\cocostest.com\Cocos2d-js-ES2016-Flow-master\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (D:\OpenServer\domains\cocostest.com\Cocos2d-js-ES2016-Flow-master\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (D:\OpenServer\domains\cocostest.com\Cocos2d-js-ES2016-Flow-master\node_modules\orchestrator\index.js:134:8)

**Comment by derofim** [comment]
Possible issiues cause windows OS
" × No binary found matching your system. It's probably not supported."
Add supported platforms in readme.md please.

**Comment by TimMensch** [comment]
Works on Windows. That's my native platform.

I missed an important setup step. Two, it looks like. You need to use Cocos2d to install a frameworks folder, and you need to set an environment variable to point at Flow:

`set FLOW_BIN=/path/to/flow`

The latter is from the gulp-flowtype docs:

https://www.npmjs.com/package/gulp-flowtype

I'll update the README. Thanks for the note.
